<HTML>
<HEAD>
<SCRIPT LANGUAGE="javascript" SRC="http://www.nyphilkids.org/common/common.js"></SCRIPT>
<META NAME="keywords" CONTENT="music, orchestra, symphony, entertainment,
kids, children, education,musical instruments, strings, woodwinds, brass,
percussion, violin, viola,cello, bass, flute, oboe, clarinet, bassoon,
piccolo, english horn, horn, french horn, trumpet, tuba, trombone, snare,
timpani, kettledrums,xylophone, bass drum, music education, classical
music, composer, musician,cymbal, symphony orchestra, conductor, saxophone,
contrabassoon, bassclarinet, instruments, new york philharmonic, new york
philharmonickidszone, fun, kidzone, harp, celeste, mazur, bernstein,
brahms, beethoven,bach, tower, amy beach, gubaidulina">
<META NAME="description" CONTENT="The New York Philharmonic Kidzone is a
place for kids to come and learn about the New York Philharmonic and about
the instruments, music, musicians, composers and conductors of symphony
music. ">
<META NAME="ROBOTS" CONTENT="ALL">
<META NAME="DC.Title" CONTENT="The New York Philharmonic Kidzone">
<META NAME="DC.Creator" CONTENT="Rebecca Krause and Wade Tinney">
<META NAME="DC.Subject" CONTENT="Symphony and Orchestral Music">
<META NAME="DC.Description" CONTENT="The New York Philharmonic Kidzone is a
place for kids to come and learn about the New York Philharmonic and about
the instruments, music, musicians, composers and conductors of the symphony
orchestra. ">
<META NAME="DC.Publisher" CONTENT="The New York Philharmonic">
<META NAME="DC.Contributors" CONTENT="Rebecca Krause, Wade Tinney, Josh
Welber, David Horvath, Shamus Kahn, Patricia Espinosa, Eli Katz, Ted Dawson, Marcia Young">
<TITLE>Composer's Gallery</TITLE>

</HEAD>
<BODY BGCOLOR=#009900>
<script language="javascript" src="http://www.nyphilkids.org/common/body.js"></script>

<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" 
codebase="http://fpdownload.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=7,0,0,0" width="100%" height="100%" id="game" align="middle">
<param name="allowScriptAccess" value="sameDomain" />
<param name="movie" value="game.swf" />
<param name="quality" value="high" />
<param name="bgcolor" value="#009900" />
<embed src="game.swf" quality="high" bgcolor="#009900" width="100%" height="100%" name="game" align="middle" allowScriptAccess="sameDomain" 
type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/go/getflashplayer" />
</object>

</BODY>

</HTML>




