<HTML>
<HEAD>
<SCRIPT LANGUAGE="javascript" SRC="http://www.nyphilkids.org/common/common.js"></SCRIPT>
<META NAME="keywords" CONTENT="music, orchestra, symphony, entertainment, 
kids, children, education,musical instruments, strings, woodwinds, brass, 
percussion, violin, viola,cello, bass, flute, oboe, clarinet, bassoon, 
piccolo, english horn, horn, french horn, trumpet, tuba, trombone, snare, 
timpani, kettledrums,xylophone, bass drum, music education, classical 
music, composer, musician,cymbal, symphony orchestra, conductor, saxophone, 
contrabassoon, bassclarinet, instruments, new york philharmonic, new york 
philharmonickidszone, fun, kidzone, harp, celeste, mazur, bernstein, 
brahms, beethoven,bach, tower, amy beach, gubaidulina">
<META NAME="description" CONTENT="The New York Philharmonic Kidzone is a 
place for kids to come and learn about the New York Philharmonic and about 
the instruments, music, musicians, composers and conductors of symphony 
music. ">
<META NAME="ROBOTS" CONTENT="ALL">
<META NAME="DC.Title" CONTENT="The New York Philharmonic Kidzone">
<META NAME="DC.Creator" CONTENT="Rebecca Krause and Wade Tinney">
<META NAME="DC.Subject" CONTENT="Symphony and Orchestral Music">
<META NAME="DC.Description" CONTENT="The New York Philharmonic Kidzone is a 
place for kids to come and learn about the New York Philharmonic and about 
the instruments, music, musicians, composers and conductors of the symphony 
orchestra. ">
<META NAME="DC.Publisher" CONTENT="The New York Philharmonic">
<META NAME="DC.Contributors" CONTENT="Rebecca Krause, Wade Tinney, Josh 
Welber, David Horvath, Shamus Kahn, Patricia Espinosa, Eli Katz, Ted Dawson, 
Marcia Young, Maria Clara Gomez">
<TITLE>New York Philharmonic</TITLE>


</HEAD>
<FRAMESET COLS="18.2%, *,1%" FRAMEBORDER="no" BORDER="0">   

<FRAME SRC="map.html" NAME="map" SCROLLING=no> 

<FRAME SRC="content.php" NAME="content" SCROLLING=auto>

</FRAMESET>


</HTML>
