<HTML>
<HEAD>
 <SCRIPT LANGUAGE="JavaScript" SRC="http://www.nyphilkids.org/common/common.js"></SCRIPT>

<META NAME=keywords CONTENT="music, orchestra, symphony, entertainment,

kids, children, education,musical instruments, strings, woodwinds, brass,
 
percussion, violin, viola,cello, bass, flute, oboe, clarinet, bassoon,
 
piccolo, english horn, horn, french horn, trumpet, tuba, trombone, snare,
 
timpani, kettledrums,xylophone, bass drum, music education, classical
 
music, composer, musician,cymbal, symphony orchestra, conductor, saxophone,
 
contrabassoon, bassclarinet, instruments, new york philharmonic, new york
 
philharmonickidszone, fun, kidzone, harp, celeste, mazur, bernstein,
 
brahms, beethoven,bach, tower, amy beach, gubaidulina">

<META NAME=description CONTENT="The New York Philharmonic Kidzone is a
 
place for kids to come and learn about the New York Philharmonic and about
 
the instruments, music, musicians, composers and conductors of symphony
 
music.">

<META NAME=ROBOTS CONTENT=ALL>

<META NAME=DC.Title CONTENT="The New York Philharmonic Kidzone">

<META NAME=DC.Creator CONTENT="Rebecca Krause and Wade Tinney">

<META NAME=DC.Subject CONTENT="Symphony and Orchestral Music">

<META NAME=DC.Description CONTENT="The New York Philharmonic Kidzone is a
 
place for kids to come and learn about the New York Philharmonic and about
 
the instruments, music, musicians, composers and conductors of the symphony
 
orchestra. ">

<META NAME="DC.Publisher" CONTENT="The New York Philharmonic">

<META NAME="DC.Contributors" CONTENT="Rebecca Krause, Wade Tinney, Maria Clara Gomez, Josh
 
Welber, David Horvath, Shamus Kahn, Patricia Espinosa, Eli Katz, Ted Dawson, Marcia Young">

<TITLE>New York Philharmonic</TITLE>

</HEAD>

<BODY TEXT="FFFF99" BGCOLOR="CC0000" LINK="FFFF99" VLINK="FFFF99" TOPMARGIN="0"><CENTER>
<SCRIPT LANGUAGE="JavaScript" SRC="http://www.nyphilkids.org/common/body.js"></SCRIPT>


<MAP NAME="stage_main">
<AREA COORDS="33,288,85,372" HREF="javascript:openTopPage('/dressingrooms/')">
<AREA COORDS="99,333,163,397" HREF="javascript:openTopPage('/newsstand/')">
<AREA COORDS="485,291,553,361" HREF="javascript:openTopPage('/studio/')">
<AREA COORDS="415,316,483,421" HREF="javascript:openTopPage('/lab/')">
<AREA COORDS="530,81,572,149" HREF="javascript:openTopPage('/lockerroom/')">
<AREA COORDS="31,81,83,143" HREF="javascript:openTopPage('/composition/')">
<AREA COORDS="501,166,563,230" HREF="javascript:openTopPage('/games/')">
<AREA COORDS="35,169,105,237" HREF="javascript:openTopPage('/gallery/')">
</MAP>

<script language="JavaScript" type="text/javascript">
<!--
// -----------------------------------------------------------------------------
// Globals
// Major version of Flash required
var requiredMajorVersion = 8;
// Minor version of Flash required
var requiredMinorVersion = 0;
// Minor version of Flash required
var requiredRevision = 0;
// the version of javascript supported
var jsVersion = 1.0;
// -----------------------------------------------------------------------------
// -->
</script>
<script language="VBScript" type="text/vbscript">
<!-- // Visual basic helper required to detect Flash Player ActiveX control version information
Function VBGetSwfVer(i)
  on error resume next
  Dim swControl, swVersion
  swVersion = 0
  
  set swControl = CreateObject("ShockwaveFlash.ShockwaveFlash." + CStr(i))
  if (IsObject(swControl)) then
    swVersion = swControl.GetVariable("$version")
  end if
  VBGetSwfVer = swVersion
End Function
// -->
</script>
<script language="JavaScript1.1" type="text/javascript">
<!-- // Detect Client Browser type
var isIE  = (navigator.appVersion.indexOf("MSIE") != -1) ? true : false;
var isWin = (navigator.appVersion.toLowerCase().indexOf("win") != -1) ? true : false;
var isOpera = (navigator.userAgent.indexOf("Opera") != -1) ? true : false;
jsVersion = 1.1;
// JavaScript helper required to detect Flash Player PlugIn version information
function JSGetSwfVer(i){
	// NS/Opera version >= 3 check for Flash plugin in plugin array
	if (navigator.plugins != null && navigator.plugins.length > 0) {
		if (navigator.plugins["Shockwave Flash 2.0"] || navigator.plugins["Shockwave Flash"]) {
			var swVer2 = navigator.plugins["Shockwave Flash 2.0"] ? " 2.0" : "";
      		var flashDescription = navigator.plugins["Shockwave Flash" + swVer2].description;
			descArray = flashDescription.split(" ");
			tempArrayMajor = descArray[2].split(".");
			versionMajor = tempArrayMajor[0];
			versionMinor = tempArrayMajor[1];
			if ( descArray[3] != "" ) {
				tempArrayMinor = descArray[3].split("r");
			} else {
				tempArrayMinor = descArray[4].split("r");
			}
      		versionRevision = tempArrayMinor[1] > 0 ? tempArrayMinor[1] : 0;
            flashVer = versionMajor + "." + versionMinor + "." + versionRevision;
      	} else {
			flashVer = -1;
		}
	}
	// MSN/WebTV 2.6 supports Flash 4
	else if (navigator.userAgent.toLowerCase().indexOf("webtv/2.6") != -1) flashVer = 4;
	// WebTV 2.5 supports Flash 3
	else if (navigator.userAgent.toLowerCase().indexOf("webtv/2.5") != -1) flashVer = 3;
	// older WebTV supports Flash 2
	else if (navigator.userAgent.toLowerCase().indexOf("webtv") != -1) flashVer = 2;
	// Can't detect in all other cases
	else {
		
		flashVer = -1;
	}
	return flashVer;
} 
// When called with reqMajorVer, reqMinorVer, reqRevision returns true if that version or greater is available
function DetectFlashVer(reqMajorVer, reqMinorVer, reqRevision) 
{
 	reqVer = parseFloat(reqMajorVer + "." + reqRevision);
   	// loop backwards through the versions until we find the newest version	
	for (i=25;i>0;i--) {	
		if (isIE && isWin && !isOpera) {
			versionStr = VBGetSwfVer(i);
		} else {
			versionStr = JSGetSwfVer(i);		
		}
		if (versionStr == -1 ) { 
			return false;
		} else if (versionStr != 0) {
			if(isIE && isWin && !isOpera) {
				tempArray         = versionStr.split(" ");
				tempString        = tempArray[1];
				versionArray      = tempString .split(",");				
			} else {
				versionArray      = versionStr.split(".");
			}
			versionMajor      = versionArray[0];
			versionMinor      = versionArray[1];
			versionRevision   = versionArray[2];
			
			versionString     = versionMajor + "." + versionRevision;   // 7.0r24 == 7.24
			versionNum        = parseFloat(versionString);
        	// is the major.revision >= requested major.revision AND the minor version >= requested minor
			if ( (versionMajor > reqMajorVer) && (versionNum >= reqVer) ) {
				return true;
			} else {
				return ((versionNum >= reqVer && versionMinor >= reqMinorVer) ? true : false );	
			}
		}
	}	
}
// -->
</script>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
	<script language=JavaScript>
	<!--
	var tMajorVersion = 10;
	var tMinorVersion = 1;
	var tShockwaveFound = 0;
	if (navigator.mimeTypes && navigator.mimeTypes["application/x-director"] && navigator.mimeTypes["application/x-director"].enabledPlugin) {
	  if (navigator.plugins && navigator.plugins["Shockwave for Director"] && (tVersionIndex = navigator.plugins["Shockwave for Director"].description.indexOf(".")) != - 1) {
	    var tMajorVersionString = navigator.plugins["Shockwave for Director"].description.substring(tVersionIndex-2, tVersionIndex);
	   var tMinorVersionString = navigator.plugins["Shockwave for Director"].description.substring(tVersionIndex+1, tVersionIndex+2);
	   if (parseInt(tMajorVersionString) >= tMajorVersion) {
	     if (tMinorVersion > 0) {
	       if (parseInt(tMinorVersionString) >= tMinorVersion) {
	         tShockwaveFound = 1;
	    }
	     } else {
	       tShockwaveFound = 1;
	     }
	    }
	  }
	} else if (navigator.userAgent && navigator.userAgent.indexOf("MSIE")>=0 && (navigator.userAgent.indexOf("Windows 95")>=0 || navigator.userAgent.indexOf("Windows 98")>=0 || navigator.userAgent.indexOf("Windows NT")>=0 )) {
	  var tVersionString = "";
	  document.write('<script language=VBScript\> \n');
	  document.write('on error resume next \n');
	  document.write('set tSWControl = CreateObject("SWCtl.SWCtl") \n');
	  document.write('if IsObject(tSWControl) then \n');
	  document.write('tVersionString = tSWControl.ShockwaveVersion("") \n');
	  document.write('end if');
	  document.write('</script\> \n');
	  if (tVersionString != "") {
	    tVersionIndex = tVersionString.indexOf(".")
	   var tMajorVersionString = tVersionString.substring(tVersionIndex-2, tVersionIndex);
	   var tMinorVersionString = tVersionString.substring(tVersionIndex+1, tVersionIndex+2);
	   if (parseInt(tMajorVersionString) >= tMajorVersion) {
	     if (tMinorVersion > 0) {
	       if (parseInt(tMinorVersionString) >= tMinorVersion) {
	         tShockwaveFound = 1;
	       }
	     } else {
	       tShockwaveFound = 1;
	     }
	   }
	  }
	}
	
	
	// Version check based upon the values entered above in "Globals"
	var hasReqestedVersion = DetectFlashVer(requiredMajorVersion, requiredMinorVersion, requiredRevision);
	
	if ( tShockwaveFound && hasReqestedVersion ) {
		document.write('<OBJECT classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000"');
		document.write('  codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,0,0" ');
		document.write(' ID="stage_main" WIDTH="100%" HEIGHT="90%" ALIGN="">');
		document.write(' <PARAM NAME=movie VALUE="stage_main.swf?type=live"> <PARAM NAME=loop VALUE=false> <PARAM NAME=menu VALUE=false> <PARAM NAME=quality VALUE=autohigh> <PARAM NAME=salign VALUE=T> <PARAM NAME=bgcolor VALUE=#CC0000>  '); 
		document.write(' <EMBED src="stage_main.swf?type=live" loop=false menu=false quality=autohigh salign=T bgcolor=#CC0000  ');
		document.write(' swLiveConnect=FALSE WIDTH="100%" HEIGHT="90%" NAME="stage_main" ALIGN=""');
		document.write(' TYPE="application/x-shockwave-flash" PLUGINSPAGE="http://www.macromedia.com/go/getflashplayer">');
		document.write(' </EMBED>');
		document.write(' </OBJECT>');
	} else if ( !(tShockwaveFound) && !(hasReqestedVersion) ) {
	  document.write('<h1>Additional plugins are needed to display the New York Philharmonic Kids website.</h1><h2>Please download and install the <em>Macromedia Flash Player</em> and <em>Macromedia Shockwave Player</em> by clicking on the links below.</h2>  <h2>It will only take a minute.</h2> <a href="http://www.macromedia.com/go/getflashplayer" target="_blank"><h1>Get the Flash Player.</h1></a>&nbsp;&nbsp;&nbsp;<a href="http://www.macromedia.com/go/getshockwaveplayer" target="_blank"><h1>Get the Shockwave Player</h1></a>');
	  }
	  else if ( !(tShockwaveFound) && (hasReqestedVersion) ) {
	  document.write('<h1>Additional plugins are needed to display the New York Philharmonic Kids website.</h1><h2>Please download and install the <em>Macromedia Shockwave Player</em> by clicking on the link below.</h2>  <h2>It will only take a minute.</h2>  <a href="http://www.macromedia.com/go/getshockwaveplayer" target="_blank"><h1>Get the Shockwave Player</h1></a>');
	  }
	  else {
	  document.write('<h1>Additional plugins are needed to display the New York Philharmonic Kids website.</h1><h2>Please download and install the <em>Macromedia Flash Player</em> by clicking on the link below.</h2>  <h2>It will only take a minute.</h2> <a href="http://www.macromedia.com/go/getflashplayer" target="_blank"><h1>Get the Flash Player</h1></a>');
	  }
	
	//-->
	</script>
<NOSCRIPT><IMG SRC="stage_main.gif" WIDTH="600" HEIGHT="400" usemap="#stage_main" BORDER=0></NOSCRIPT>

<BR>

    <FONT FACE="arial, helvetica, sans" SIZE="-2"> <font face="Verdana, Arial, Helvetica, sans-serif"> 
<a href="/games/" target="_top">Game Room</a>
<A href="./studio/" target="_top">Musicians' Lounge</a>
<A HREF="./gallery/" TARGET="_top">Composers' Gallery</A> 
<A HREF="./lockerroom/" TARGET="_top">Instrument Storage Room</A> 
<A HREF="./lab/" TARGET="_top">Instrument Laboratory</A> 
<A HREF="./dressingrooms/" TARGET="_top">Conductor/Soloist Dressing Rooms</A> 
<A HREF="./newsstand/" TARGET="_top">Newsstand</A> 
<A HREF="./composition/" TARGET="_top">Composition Workshop</A></font></FONT></p>

  <p><FONT FACE="arial, helvetica, sans" SIZE="-2"><br>
    <font face="Verdana, Arial, Helvetica, sans-serif">Do you want to go to the 
    New York Philharmonic main website? <a href="http://www.newyorkphilharmonic.org" target="_blank">http://www.newyorkphilharmonic.org</a></font> 
    <BR>
    <BR>
    <font face="Verdana, Arial, Helvetica, sans-serif"><a href="./common/help.html" target="_blank">Having 
    trouble seeing the Kidzone?</a></font></FONT>
<BR>
<BR>


</CENTER>
</BODY>
</HTML>
